[package]
name = "api-99bugs-display"
version = "0.1.0"
authors = ["Sille Van Landschoot <info@sillevl.be>"]

[dependencies]
iron = "0.6.*"
router = "0.6.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bodyparser = "0.8.0"
image = "0.23"
driver_99bugs_display = "0.1.0"
